export { Coin } from '#svg/Coin.tsx';
export { default as Coupon } from '#svg/Coupon.tsx';
export { default as DLogo } from '#svg/DLogo.tsx';
export { default as DocshuntIcon } from '#svg/DocshuntIcon.tsx';
export { default as DocshuntLogo } from '#svg/DocshuntLogo.tsx';
export { default as DocshuntLogo2 } from '#svg/DocshuntLogo2.tsx';
export { default as DonutChart } from '#svg/DonutChart.tsx';
export { default as FlowChart } from '#svg/FlowChart.tsx';
export { default as FilePlusCorner } from '#svg/FilePlusCorner.tsx';
export { default as Google } from '#svg/Google.tsx';
export { default as IcHeading2Toggle } from '#svg/IcHeading2Toggle.tsx';
export { default as IcHeading3Toggle } from '#svg/IcHeading3Toggle.tsx';
export { default as IcHeadingToggle } from '#svg/IcHeadingToggle.tsx';
export { default as IcInfoTooltip } from '#svg/IcInfoTooltip.tsx';
export { default as IcQuote } from '#svg/IcQuote.tsx';
export { default as Internet } from '#svg/Internet.tsx';
export { default as Meatball } from '#svg/Meatball.tsx';
export { default as MixedChart } from '#svg/MixedChart.tsx';
export { default as PositioningMap } from '#svg/PositioningMap.tsx';
export { default as Tamsamsom } from '#svg/Tamsamsom.tsx';
export { default as SourceDefault } from '#svg/SourceDefault.tsx';
export { StyledSvg } from '#svg/svg.style.ts';
export type { SvgProps } from '#svg/svg.style.ts';
