/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroRouteImport } from './routes/_intro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntroLoginRouteImport } from './routes/_intro/login'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedTemplatePreprocessRouteRouteImport } from './routes/_authenticated/template-preprocess/route'
import { Route as AuthenticatedTemplateListRouteRouteImport } from './routes/_authenticated/template-list/route'
import { Route as AuthenticatedTemplateRouteRouteImport } from './routes/_authenticated/template/route'
import { Route as AuthenticatedMainRouteRouteImport } from './routes/_authenticated/main/route'
import { Route as AuthenticatedCouponsRouteRouteImport } from './routes/_authenticated/coupons/route'

const IntroRoute = IntroRouteImport.update({
  id: '/_intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroLoginRoute = IntroLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => IntroRoute,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatePreprocessRouteRoute =
  AuthenticatedTemplatePreprocessRouteRouteImport.update({
    id: '/template-preprocess',
    path: '/template-preprocess',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplateListRouteRoute =
  AuthenticatedTemplateListRouteRouteImport.update({
    id: '/template-list',
    path: '/template-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplateRouteRoute =
  AuthenticatedTemplateRouteRouteImport.update({
    id: '/template',
    path: '/template',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainRouteRoute = AuthenticatedMainRouteRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCouponsRouteRoute =
  AuthenticatedCouponsRouteRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coupons': typeof AuthenticatedCouponsRouteRoute
  '/main': typeof AuthenticatedMainRouteRoute
  '/template': typeof AuthenticatedTemplateRouteRoute
  '/template-list': typeof AuthenticatedTemplateListRouteRoute
  '/template-preprocess': typeof AuthenticatedTemplatePreprocessRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/login': typeof IntroLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupons': typeof AuthenticatedCouponsRouteRoute
  '/main': typeof AuthenticatedMainRouteRoute
  '/template': typeof AuthenticatedTemplateRouteRoute
  '/template-list': typeof AuthenticatedTemplateListRouteRoute
  '/template-preprocess': typeof AuthenticatedTemplatePreprocessRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/login': typeof IntroLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_intro': typeof IntroRouteWithChildren
  '/_authenticated/coupons': typeof AuthenticatedCouponsRouteRoute
  '/_authenticated/main': typeof AuthenticatedMainRouteRoute
  '/_authenticated/template': typeof AuthenticatedTemplateRouteRoute
  '/_authenticated/template-list': typeof AuthenticatedTemplateListRouteRoute
  '/_authenticated/template-preprocess': typeof AuthenticatedTemplatePreprocessRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/_intro/login': typeof IntroLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coupons'
    | '/main'
    | '/template'
    | '/template-list'
    | '/template-preprocess'
    | '/users'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coupons'
    | '/main'
    | '/template'
    | '/template-list'
    | '/template-preprocess'
    | '/users'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_intro'
    | '/_authenticated/coupons'
    | '/_authenticated/main'
    | '/_authenticated/template'
    | '/_authenticated/template-list'
    | '/_authenticated/template-preprocess'
    | '/_authenticated/users'
    | '/_intro/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  IntroRoute: typeof IntroRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_intro': {
      id: '/_intro'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_intro/login': {
      id: '/_intro/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof IntroLoginRouteImport
      parentRoute: typeof IntroRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/template-preprocess': {
      id: '/_authenticated/template-preprocess'
      path: '/template-preprocess'
      fullPath: '/template-preprocess'
      preLoaderRoute: typeof AuthenticatedTemplatePreprocessRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/template-list': {
      id: '/_authenticated/template-list'
      path: '/template-list'
      fullPath: '/template-list'
      preLoaderRoute: typeof AuthenticatedTemplateListRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/template': {
      id: '/_authenticated/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof AuthenticatedTemplateRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCouponsRouteRoute: typeof AuthenticatedCouponsRouteRoute
  AuthenticatedMainRouteRoute: typeof AuthenticatedMainRouteRoute
  AuthenticatedTemplateRouteRoute: typeof AuthenticatedTemplateRouteRoute
  AuthenticatedTemplateListRouteRoute: typeof AuthenticatedTemplateListRouteRoute
  AuthenticatedTemplatePreprocessRouteRoute: typeof AuthenticatedTemplatePreprocessRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCouponsRouteRoute: AuthenticatedCouponsRouteRoute,
  AuthenticatedMainRouteRoute: AuthenticatedMainRouteRoute,
  AuthenticatedTemplateRouteRoute: AuthenticatedTemplateRouteRoute,
  AuthenticatedTemplateListRouteRoute: AuthenticatedTemplateListRouteRoute,
  AuthenticatedTemplatePreprocessRouteRoute:
    AuthenticatedTemplatePreprocessRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface IntroRouteChildren {
  IntroLoginRoute: typeof IntroLoginRoute
}

const IntroRouteChildren: IntroRouteChildren = {
  IntroLoginRoute: IntroLoginRoute,
}

const IntroRouteWithChildren = IntroRoute._addFileChildren(IntroRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  IntroRoute: IntroRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
