/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroRouteImport } from './routes/_intro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntroSignUpRouteImport } from './routes/_intro/sign-up'
import { Route as IntroPasswordResetRouteImport } from './routes/_intro/password-reset'
import { Route as IntroAuthenticatedRouteImport } from './routes/_intro/_authenticated'
import { Route as AuthenticatedStart2RouteRouteImport } from './routes/_authenticated/start2/route'
import { Route as AuthenticatedStartRouteRouteImport } from './routes/_authenticated/start/route'
import { Route as AuthenticatedReviewRouteRouteImport } from './routes/_authenticated/review/route'
import { Route as AuthenticatedReferralEventRouteRouteImport } from './routes/_authenticated/referral-event/route'
import { Route as AuthenticatedHomepageFlowRouteRouteImport } from './routes/_authenticated/homepage-flow/route'
import { Route as AuthenticatedFRouteRouteImport } from './routes/_authenticated/f/route'
import { Route as AuthenticatedCreditPolicyRouteRouteImport } from './routes/_authenticated/credit-policy/route'
import { Route as AuthenticatedCreditPlanRouteRouteImport } from './routes/_authenticated/credit-plan/route'
import { Route as AuthenticatedCompanyRouteRouteImport } from './routes/_authenticated/company/route'
import { Route as AuthenticatedChatbotFlowRouteRouteImport } from './routes/_authenticated/chatbot-flow/route'
import { Route as AuthenticatedAdminDemoRouteRouteImport } from './routes/_authenticated/admin-demo/route'
import { Route as AuthenticatedFIndexRouteImport } from './routes/_authenticated/f/index'
import { Route as AuthenticatedDIndexRouteImport } from './routes/_authenticated/d/index'
import { Route as AuthenticatedCIndexRouteImport } from './routes/_authenticated/c/index'
import { Route as AuthenticatedAdminDemoIndexRouteImport } from './routes/_authenticated/admin-demo/index'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment/success'
import { Route as AuthenticatedPaymentFailRouteImport } from './routes/_authenticated/payment/fail'
import { Route as AuthenticatedDProductFileIdRouteImport } from './routes/_authenticated/d/$productFileId'
import { Route as AuthenticatedCProductIdRouteImport } from './routes/_authenticated/c/$productId'
import { Route as AuthenticatedDPreviewRouteRouteImport } from './routes/_authenticated/d/preview/route'
import { Route as AuthenticatedCDetailInputRouteRouteImport } from './routes/_authenticated/c/detail-input/route'
import { Route as AuthenticatedAdminDemoQualityRouteRouteImport } from './routes/_authenticated/admin-demo/quality/route'
import { Route as AuthenticatedAdminDemoOrganizationsRouteRouteImport } from './routes/_authenticated/admin-demo/organizations/route'
import { Route as AuthenticatedAdminDemoDocumentsRouteRouteImport } from './routes/_authenticated/admin-demo/documents/route'
import { Route as IntroAuthenticatedSelectOnboardingIndexRouteImport } from './routes/_intro/_authenticated/select-onboarding/index'
import { Route as AuthenticatedFTemplateIndexRouteImport } from './routes/_authenticated/f/template/index'
import { Route as AuthenticatedAdminDemoUsersIndexRouteImport } from './routes/_authenticated/admin-demo/users/index'
import { Route as AuthenticatedFVisualSuggestionsProductFileIdRouteImport } from './routes/_authenticated/f/visual-suggestions/$productFileId'
import { Route as AuthenticatedFUploadProductFileIdRouteImport } from './routes/_authenticated/f/upload/$productFileId'
import { Route as AuthenticatedFSettingsProductFileIdRouteImport } from './routes/_authenticated/f/settings/$productFileId'
import { Route as AuthenticatedFPromptProductFileIdRouteImport } from './routes/_authenticated/f/prompt/$productFileId'
import { Route as AuthenticatedFOutputProductFileIdRouteImport } from './routes/_authenticated/f/output/$productFileId'
import { Route as AuthenticatedAdminDemoUsersUserIdRouteImport } from './routes/_authenticated/admin-demo/users/$userId'

const IntroRoute = IntroRouteImport.update({
  id: '/_intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroSignUpRoute = IntroSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => IntroRoute,
} as any)
const IntroPasswordResetRoute = IntroPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => IntroRoute,
} as any)
const IntroAuthenticatedRoute = IntroAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => IntroRoute,
} as any)
const AuthenticatedStart2RouteRoute =
  AuthenticatedStart2RouteRouteImport.update({
    id: '/start2',
    path: '/start2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStartRouteRoute = AuthenticatedStartRouteRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRouteRoute =
  AuthenticatedReviewRouteRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralEventRouteRoute =
  AuthenticatedReferralEventRouteRouteImport.update({
    id: '/referral-event',
    path: '/referral-event',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomepageFlowRouteRoute =
  AuthenticatedHomepageFlowRouteRouteImport.update({
    id: '/homepage-flow',
    path: '/homepage-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFRouteRoute = AuthenticatedFRouteRouteImport.update({
  id: '/f',
  path: '/f',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditPolicyRouteRoute =
  AuthenticatedCreditPolicyRouteRouteImport.update({
    id: '/credit-policy',
    path: '/credit-policy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditPlanRouteRoute =
  AuthenticatedCreditPlanRouteRouteImport.update({
    id: '/credit-plan',
    path: '/credit-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRouteRoute =
  AuthenticatedCompanyRouteRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotFlowRouteRoute =
  AuthenticatedChatbotFlowRouteRouteImport.update({
    id: '/chatbot-flow',
    path: '/chatbot-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDemoRouteRoute =
  AuthenticatedAdminDemoRouteRouteImport.update({
    id: '/admin-demo',
    path: '/admin-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFIndexRoute = AuthenticatedFIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFRouteRoute,
} as any)
const AuthenticatedDIndexRoute = AuthenticatedDIndexRouteImport.update({
  id: '/d/',
  path: '/d/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCIndexRoute = AuthenticatedCIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDemoIndexRoute =
  AuthenticatedAdminDemoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentFailRoute =
  AuthenticatedPaymentFailRouteImport.update({
    id: '/payment/fail',
    path: '/payment/fail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDProductFileIdRoute =
  AuthenticatedDProductFileIdRouteImport.update({
    id: '/d/$productFileId',
    path: '/d/$productFileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCProductIdRoute = AuthenticatedCProductIdRouteImport.update({
  id: '/c/$productId',
  path: '/c/$productId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDPreviewRouteRoute =
  AuthenticatedDPreviewRouteRouteImport.update({
    id: '/d/preview',
    path: '/d/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCDetailInputRouteRoute =
  AuthenticatedCDetailInputRouteRouteImport.update({
    id: '/c/detail-input',
    path: '/c/detail-input',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDemoQualityRouteRoute =
  AuthenticatedAdminDemoQualityRouteRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)
const AuthenticatedAdminDemoOrganizationsRouteRoute =
  AuthenticatedAdminDemoOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)
const AuthenticatedAdminDemoDocumentsRouteRoute =
  AuthenticatedAdminDemoDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)
const IntroAuthenticatedSelectOnboardingIndexRoute =
  IntroAuthenticatedSelectOnboardingIndexRouteImport.update({
    id: '/select-onboarding/',
    path: '/select-onboarding/',
    getParentRoute: () => IntroAuthenticatedRoute,
  } as any)
const AuthenticatedFTemplateIndexRoute =
  AuthenticatedFTemplateIndexRouteImport.update({
    id: '/template/',
    path: '/template/',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedAdminDemoUsersIndexRoute =
  AuthenticatedAdminDemoUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)
const AuthenticatedFVisualSuggestionsProductFileIdRoute =
  AuthenticatedFVisualSuggestionsProductFileIdRouteImport.update({
    id: '/visual-suggestions/$productFileId',
    path: '/visual-suggestions/$productFileId',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedFUploadProductFileIdRoute =
  AuthenticatedFUploadProductFileIdRouteImport.update({
    id: '/upload/$productFileId',
    path: '/upload/$productFileId',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedFSettingsProductFileIdRoute =
  AuthenticatedFSettingsProductFileIdRouteImport.update({
    id: '/settings/$productFileId',
    path: '/settings/$productFileId',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedFPromptProductFileIdRoute =
  AuthenticatedFPromptProductFileIdRouteImport.update({
    id: '/prompt/$productFileId',
    path: '/prompt/$productFileId',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedFOutputProductFileIdRoute =
  AuthenticatedFOutputProductFileIdRouteImport.update({
    id: '/output/$productFileId',
    path: '/output/$productFileId',
    getParentRoute: () => AuthenticatedFRouteRoute,
  } as any)
const AuthenticatedAdminDemoUsersUserIdRoute =
  AuthenticatedAdminDemoUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminDemoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-demo': typeof AuthenticatedAdminDemoRouteRouteWithChildren
  '/chatbot-flow': typeof AuthenticatedChatbotFlowRouteRoute
  '/company': typeof AuthenticatedCompanyRouteRoute
  '/credit-plan': typeof AuthenticatedCreditPlanRouteRoute
  '/credit-policy': typeof AuthenticatedCreditPolicyRouteRoute
  '/f': typeof AuthenticatedFRouteRouteWithChildren
  '/homepage-flow': typeof AuthenticatedHomepageFlowRouteRoute
  '/referral-event': typeof AuthenticatedReferralEventRouteRoute
  '/review': typeof AuthenticatedReviewRouteRoute
  '/start': typeof AuthenticatedStartRouteRoute
  '/start2': typeof AuthenticatedStart2RouteRoute
  '/password-reset': typeof IntroPasswordResetRoute
  '/sign-up': typeof IntroSignUpRoute
  '/admin-demo/documents': typeof AuthenticatedAdminDemoDocumentsRouteRoute
  '/admin-demo/organizations': typeof AuthenticatedAdminDemoOrganizationsRouteRoute
  '/admin-demo/quality': typeof AuthenticatedAdminDemoQualityRouteRoute
  '/c/detail-input': typeof AuthenticatedCDetailInputRouteRoute
  '/d/preview': typeof AuthenticatedDPreviewRouteRoute
  '/c/$productId': typeof AuthenticatedCProductIdRoute
  '/d/$productFileId': typeof AuthenticatedDProductFileIdRoute
  '/payment/fail': typeof AuthenticatedPaymentFailRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin-demo/': typeof AuthenticatedAdminDemoIndexRoute
  '/c': typeof AuthenticatedCIndexRoute
  '/d': typeof AuthenticatedDIndexRoute
  '/f/': typeof AuthenticatedFIndexRoute
  '/admin-demo/users/$userId': typeof AuthenticatedAdminDemoUsersUserIdRoute
  '/f/output/$productFileId': typeof AuthenticatedFOutputProductFileIdRoute
  '/f/prompt/$productFileId': typeof AuthenticatedFPromptProductFileIdRoute
  '/f/settings/$productFileId': typeof AuthenticatedFSettingsProductFileIdRoute
  '/f/upload/$productFileId': typeof AuthenticatedFUploadProductFileIdRoute
  '/f/visual-suggestions/$productFileId': typeof AuthenticatedFVisualSuggestionsProductFileIdRoute
  '/admin-demo/users': typeof AuthenticatedAdminDemoUsersIndexRoute
  '/f/template': typeof AuthenticatedFTemplateIndexRoute
  '/select-onboarding': typeof IntroAuthenticatedSelectOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot-flow': typeof AuthenticatedChatbotFlowRouteRoute
  '/company': typeof AuthenticatedCompanyRouteRoute
  '/credit-plan': typeof AuthenticatedCreditPlanRouteRoute
  '/credit-policy': typeof AuthenticatedCreditPolicyRouteRoute
  '/homepage-flow': typeof AuthenticatedHomepageFlowRouteRoute
  '/referral-event': typeof AuthenticatedReferralEventRouteRoute
  '/review': typeof AuthenticatedReviewRouteRoute
  '/start': typeof AuthenticatedStartRouteRoute
  '/start2': typeof AuthenticatedStart2RouteRoute
  '/password-reset': typeof IntroPasswordResetRoute
  '/sign-up': typeof IntroSignUpRoute
  '/admin-demo/documents': typeof AuthenticatedAdminDemoDocumentsRouteRoute
  '/admin-demo/organizations': typeof AuthenticatedAdminDemoOrganizationsRouteRoute
  '/admin-demo/quality': typeof AuthenticatedAdminDemoQualityRouteRoute
  '/c/detail-input': typeof AuthenticatedCDetailInputRouteRoute
  '/d/preview': typeof AuthenticatedDPreviewRouteRoute
  '/c/$productId': typeof AuthenticatedCProductIdRoute
  '/d/$productFileId': typeof AuthenticatedDProductFileIdRoute
  '/payment/fail': typeof AuthenticatedPaymentFailRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin-demo': typeof AuthenticatedAdminDemoIndexRoute
  '/c': typeof AuthenticatedCIndexRoute
  '/d': typeof AuthenticatedDIndexRoute
  '/f': typeof AuthenticatedFIndexRoute
  '/admin-demo/users/$userId': typeof AuthenticatedAdminDemoUsersUserIdRoute
  '/f/output/$productFileId': typeof AuthenticatedFOutputProductFileIdRoute
  '/f/prompt/$productFileId': typeof AuthenticatedFPromptProductFileIdRoute
  '/f/settings/$productFileId': typeof AuthenticatedFSettingsProductFileIdRoute
  '/f/upload/$productFileId': typeof AuthenticatedFUploadProductFileIdRoute
  '/f/visual-suggestions/$productFileId': typeof AuthenticatedFVisualSuggestionsProductFileIdRoute
  '/admin-demo/users': typeof AuthenticatedAdminDemoUsersIndexRoute
  '/f/template': typeof AuthenticatedFTemplateIndexRoute
  '/select-onboarding': typeof IntroAuthenticatedSelectOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_intro': typeof IntroRouteWithChildren
  '/_authenticated/admin-demo': typeof AuthenticatedAdminDemoRouteRouteWithChildren
  '/_authenticated/chatbot-flow': typeof AuthenticatedChatbotFlowRouteRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRouteRoute
  '/_authenticated/credit-plan': typeof AuthenticatedCreditPlanRouteRoute
  '/_authenticated/credit-policy': typeof AuthenticatedCreditPolicyRouteRoute
  '/_authenticated/f': typeof AuthenticatedFRouteRouteWithChildren
  '/_authenticated/homepage-flow': typeof AuthenticatedHomepageFlowRouteRoute
  '/_authenticated/referral-event': typeof AuthenticatedReferralEventRouteRoute
  '/_authenticated/review': typeof AuthenticatedReviewRouteRoute
  '/_authenticated/start': typeof AuthenticatedStartRouteRoute
  '/_authenticated/start2': typeof AuthenticatedStart2RouteRoute
  '/_intro/_authenticated': typeof IntroAuthenticatedRouteWithChildren
  '/_intro/password-reset': typeof IntroPasswordResetRoute
  '/_intro/sign-up': typeof IntroSignUpRoute
  '/_authenticated/admin-demo/documents': typeof AuthenticatedAdminDemoDocumentsRouteRoute
  '/_authenticated/admin-demo/organizations': typeof AuthenticatedAdminDemoOrganizationsRouteRoute
  '/_authenticated/admin-demo/quality': typeof AuthenticatedAdminDemoQualityRouteRoute
  '/_authenticated/c/detail-input': typeof AuthenticatedCDetailInputRouteRoute
  '/_authenticated/d/preview': typeof AuthenticatedDPreviewRouteRoute
  '/_authenticated/c/$productId': typeof AuthenticatedCProductIdRoute
  '/_authenticated/d/$productFileId': typeof AuthenticatedDProductFileIdRoute
  '/_authenticated/payment/fail': typeof AuthenticatedPaymentFailRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/_authenticated/admin-demo/': typeof AuthenticatedAdminDemoIndexRoute
  '/_authenticated/c/': typeof AuthenticatedCIndexRoute
  '/_authenticated/d/': typeof AuthenticatedDIndexRoute
  '/_authenticated/f/': typeof AuthenticatedFIndexRoute
  '/_authenticated/admin-demo/users/$userId': typeof AuthenticatedAdminDemoUsersUserIdRoute
  '/_authenticated/f/output/$productFileId': typeof AuthenticatedFOutputProductFileIdRoute
  '/_authenticated/f/prompt/$productFileId': typeof AuthenticatedFPromptProductFileIdRoute
  '/_authenticated/f/settings/$productFileId': typeof AuthenticatedFSettingsProductFileIdRoute
  '/_authenticated/f/upload/$productFileId': typeof AuthenticatedFUploadProductFileIdRoute
  '/_authenticated/f/visual-suggestions/$productFileId': typeof AuthenticatedFVisualSuggestionsProductFileIdRoute
  '/_authenticated/admin-demo/users/': typeof AuthenticatedAdminDemoUsersIndexRoute
  '/_authenticated/f/template/': typeof AuthenticatedFTemplateIndexRoute
  '/_intro/_authenticated/select-onboarding/': typeof IntroAuthenticatedSelectOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-demo'
    | '/chatbot-flow'
    | '/company'
    | '/credit-plan'
    | '/credit-policy'
    | '/f'
    | '/homepage-flow'
    | '/referral-event'
    | '/review'
    | '/start'
    | '/start2'
    | '/password-reset'
    | '/sign-up'
    | '/admin-demo/documents'
    | '/admin-demo/organizations'
    | '/admin-demo/quality'
    | '/c/detail-input'
    | '/d/preview'
    | '/c/$productId'
    | '/d/$productFileId'
    | '/payment/fail'
    | '/payment/success'
    | '/admin-demo/'
    | '/c'
    | '/d'
    | '/f/'
    | '/admin-demo/users/$userId'
    | '/f/output/$productFileId'
    | '/f/prompt/$productFileId'
    | '/f/settings/$productFileId'
    | '/f/upload/$productFileId'
    | '/f/visual-suggestions/$productFileId'
    | '/admin-demo/users'
    | '/f/template'
    | '/select-onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot-flow'
    | '/company'
    | '/credit-plan'
    | '/credit-policy'
    | '/homepage-flow'
    | '/referral-event'
    | '/review'
    | '/start'
    | '/start2'
    | '/password-reset'
    | '/sign-up'
    | '/admin-demo/documents'
    | '/admin-demo/organizations'
    | '/admin-demo/quality'
    | '/c/detail-input'
    | '/d/preview'
    | '/c/$productId'
    | '/d/$productFileId'
    | '/payment/fail'
    | '/payment/success'
    | '/admin-demo'
    | '/c'
    | '/d'
    | '/f'
    | '/admin-demo/users/$userId'
    | '/f/output/$productFileId'
    | '/f/prompt/$productFileId'
    | '/f/settings/$productFileId'
    | '/f/upload/$productFileId'
    | '/f/visual-suggestions/$productFileId'
    | '/admin-demo/users'
    | '/f/template'
    | '/select-onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_intro'
    | '/_authenticated/admin-demo'
    | '/_authenticated/chatbot-flow'
    | '/_authenticated/company'
    | '/_authenticated/credit-plan'
    | '/_authenticated/credit-policy'
    | '/_authenticated/f'
    | '/_authenticated/homepage-flow'
    | '/_authenticated/referral-event'
    | '/_authenticated/review'
    | '/_authenticated/start'
    | '/_authenticated/start2'
    | '/_intro/_authenticated'
    | '/_intro/password-reset'
    | '/_intro/sign-up'
    | '/_authenticated/admin-demo/documents'
    | '/_authenticated/admin-demo/organizations'
    | '/_authenticated/admin-demo/quality'
    | '/_authenticated/c/detail-input'
    | '/_authenticated/d/preview'
    | '/_authenticated/c/$productId'
    | '/_authenticated/d/$productFileId'
    | '/_authenticated/payment/fail'
    | '/_authenticated/payment/success'
    | '/_authenticated/admin-demo/'
    | '/_authenticated/c/'
    | '/_authenticated/d/'
    | '/_authenticated/f/'
    | '/_authenticated/admin-demo/users/$userId'
    | '/_authenticated/f/output/$productFileId'
    | '/_authenticated/f/prompt/$productFileId'
    | '/_authenticated/f/settings/$productFileId'
    | '/_authenticated/f/upload/$productFileId'
    | '/_authenticated/f/visual-suggestions/$productFileId'
    | '/_authenticated/admin-demo/users/'
    | '/_authenticated/f/template/'
    | '/_intro/_authenticated/select-onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  IntroRoute: typeof IntroRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_intro': {
      id: '/_intro'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_intro/sign-up': {
      id: '/_intro/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof IntroSignUpRouteImport
      parentRoute: typeof IntroRoute
    }
    '/_intro/password-reset': {
      id: '/_intro/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof IntroPasswordResetRouteImport
      parentRoute: typeof IntroRoute
    }
    '/_intro/_authenticated': {
      id: '/_intro/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IntroAuthenticatedRouteImport
      parentRoute: typeof IntroRoute
    }
    '/_authenticated/start2': {
      id: '/_authenticated/start2'
      path: '/start2'
      fullPath: '/start2'
      preLoaderRoute: typeof AuthenticatedStart2RouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral-event': {
      id: '/_authenticated/referral-event'
      path: '/referral-event'
      fullPath: '/referral-event'
      preLoaderRoute: typeof AuthenticatedReferralEventRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homepage-flow': {
      id: '/_authenticated/homepage-flow'
      path: '/homepage-flow'
      fullPath: '/homepage-flow'
      preLoaderRoute: typeof AuthenticatedHomepageFlowRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/f': {
      id: '/_authenticated/f'
      path: '/f'
      fullPath: '/f'
      preLoaderRoute: typeof AuthenticatedFRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-policy': {
      id: '/_authenticated/credit-policy'
      path: '/credit-policy'
      fullPath: '/credit-policy'
      preLoaderRoute: typeof AuthenticatedCreditPolicyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-plan': {
      id: '/_authenticated/credit-plan'
      path: '/credit-plan'
      fullPath: '/credit-plan'
      preLoaderRoute: typeof AuthenticatedCreditPlanRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot-flow': {
      id: '/_authenticated/chatbot-flow'
      path: '/chatbot-flow'
      fullPath: '/chatbot-flow'
      preLoaderRoute: typeof AuthenticatedChatbotFlowRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-demo': {
      id: '/_authenticated/admin-demo'
      path: '/admin-demo'
      fullPath: '/admin-demo'
      preLoaderRoute: typeof AuthenticatedAdminDemoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/f/': {
      id: '/_authenticated/f/'
      path: '/'
      fullPath: '/f/'
      preLoaderRoute: typeof AuthenticatedFIndexRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/d/': {
      id: '/_authenticated/d/'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof AuthenticatedDIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/': {
      id: '/_authenticated/c/'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof AuthenticatedCIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-demo/': {
      id: '/_authenticated/admin-demo/'
      path: '/'
      fullPath: '/admin-demo/'
      preLoaderRoute: typeof AuthenticatedAdminDemoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/fail': {
      id: '/_authenticated/payment/fail'
      path: '/payment/fail'
      fullPath: '/payment/fail'
      preLoaderRoute: typeof AuthenticatedPaymentFailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/d/$productFileId': {
      id: '/_authenticated/d/$productFileId'
      path: '/d/$productFileId'
      fullPath: '/d/$productFileId'
      preLoaderRoute: typeof AuthenticatedDProductFileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$productId': {
      id: '/_authenticated/c/$productId'
      path: '/c/$productId'
      fullPath: '/c/$productId'
      preLoaderRoute: typeof AuthenticatedCProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/d/preview': {
      id: '/_authenticated/d/preview'
      path: '/d/preview'
      fullPath: '/d/preview'
      preLoaderRoute: typeof AuthenticatedDPreviewRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/detail-input': {
      id: '/_authenticated/c/detail-input'
      path: '/c/detail-input'
      fullPath: '/c/detail-input'
      preLoaderRoute: typeof AuthenticatedCDetailInputRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-demo/quality': {
      id: '/_authenticated/admin-demo/quality'
      path: '/quality'
      fullPath: '/admin-demo/quality'
      preLoaderRoute: typeof AuthenticatedAdminDemoQualityRouteRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
    '/_authenticated/admin-demo/organizations': {
      id: '/_authenticated/admin-demo/organizations'
      path: '/organizations'
      fullPath: '/admin-demo/organizations'
      preLoaderRoute: typeof AuthenticatedAdminDemoOrganizationsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
    '/_authenticated/admin-demo/documents': {
      id: '/_authenticated/admin-demo/documents'
      path: '/documents'
      fullPath: '/admin-demo/documents'
      preLoaderRoute: typeof AuthenticatedAdminDemoDocumentsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
    '/_intro/_authenticated/select-onboarding/': {
      id: '/_intro/_authenticated/select-onboarding/'
      path: '/select-onboarding'
      fullPath: '/select-onboarding'
      preLoaderRoute: typeof IntroAuthenticatedSelectOnboardingIndexRouteImport
      parentRoute: typeof IntroAuthenticatedRoute
    }
    '/_authenticated/f/template/': {
      id: '/_authenticated/f/template/'
      path: '/template'
      fullPath: '/f/template'
      preLoaderRoute: typeof AuthenticatedFTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/admin-demo/users/': {
      id: '/_authenticated/admin-demo/users/'
      path: '/users'
      fullPath: '/admin-demo/users'
      preLoaderRoute: typeof AuthenticatedAdminDemoUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
    '/_authenticated/f/visual-suggestions/$productFileId': {
      id: '/_authenticated/f/visual-suggestions/$productFileId'
      path: '/visual-suggestions/$productFileId'
      fullPath: '/f/visual-suggestions/$productFileId'
      preLoaderRoute: typeof AuthenticatedFVisualSuggestionsProductFileIdRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/f/upload/$productFileId': {
      id: '/_authenticated/f/upload/$productFileId'
      path: '/upload/$productFileId'
      fullPath: '/f/upload/$productFileId'
      preLoaderRoute: typeof AuthenticatedFUploadProductFileIdRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/f/settings/$productFileId': {
      id: '/_authenticated/f/settings/$productFileId'
      path: '/settings/$productFileId'
      fullPath: '/f/settings/$productFileId'
      preLoaderRoute: typeof AuthenticatedFSettingsProductFileIdRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/f/prompt/$productFileId': {
      id: '/_authenticated/f/prompt/$productFileId'
      path: '/prompt/$productFileId'
      fullPath: '/f/prompt/$productFileId'
      preLoaderRoute: typeof AuthenticatedFPromptProductFileIdRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/f/output/$productFileId': {
      id: '/_authenticated/f/output/$productFileId'
      path: '/output/$productFileId'
      fullPath: '/f/output/$productFileId'
      preLoaderRoute: typeof AuthenticatedFOutputProductFileIdRouteImport
      parentRoute: typeof AuthenticatedFRouteRoute
    }
    '/_authenticated/admin-demo/users/$userId': {
      id: '/_authenticated/admin-demo/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin-demo/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminDemoUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminDemoRouteRoute
    }
  }
}

interface AuthenticatedAdminDemoRouteRouteChildren {
  AuthenticatedAdminDemoDocumentsRouteRoute: typeof AuthenticatedAdminDemoDocumentsRouteRoute
  AuthenticatedAdminDemoOrganizationsRouteRoute: typeof AuthenticatedAdminDemoOrganizationsRouteRoute
  AuthenticatedAdminDemoQualityRouteRoute: typeof AuthenticatedAdminDemoQualityRouteRoute
  AuthenticatedAdminDemoIndexRoute: typeof AuthenticatedAdminDemoIndexRoute
  AuthenticatedAdminDemoUsersUserIdRoute: typeof AuthenticatedAdminDemoUsersUserIdRoute
  AuthenticatedAdminDemoUsersIndexRoute: typeof AuthenticatedAdminDemoUsersIndexRoute
}

const AuthenticatedAdminDemoRouteRouteChildren: AuthenticatedAdminDemoRouteRouteChildren =
  {
    AuthenticatedAdminDemoDocumentsRouteRoute:
      AuthenticatedAdminDemoDocumentsRouteRoute,
    AuthenticatedAdminDemoOrganizationsRouteRoute:
      AuthenticatedAdminDemoOrganizationsRouteRoute,
    AuthenticatedAdminDemoQualityRouteRoute:
      AuthenticatedAdminDemoQualityRouteRoute,
    AuthenticatedAdminDemoIndexRoute: AuthenticatedAdminDemoIndexRoute,
    AuthenticatedAdminDemoUsersUserIdRoute:
      AuthenticatedAdminDemoUsersUserIdRoute,
    AuthenticatedAdminDemoUsersIndexRoute:
      AuthenticatedAdminDemoUsersIndexRoute,
  }

const AuthenticatedAdminDemoRouteRouteWithChildren =
  AuthenticatedAdminDemoRouteRoute._addFileChildren(
    AuthenticatedAdminDemoRouteRouteChildren,
  )

interface AuthenticatedFRouteRouteChildren {
  AuthenticatedFIndexRoute: typeof AuthenticatedFIndexRoute
  AuthenticatedFOutputProductFileIdRoute: typeof AuthenticatedFOutputProductFileIdRoute
  AuthenticatedFPromptProductFileIdRoute: typeof AuthenticatedFPromptProductFileIdRoute
  AuthenticatedFSettingsProductFileIdRoute: typeof AuthenticatedFSettingsProductFileIdRoute
  AuthenticatedFUploadProductFileIdRoute: typeof AuthenticatedFUploadProductFileIdRoute
  AuthenticatedFVisualSuggestionsProductFileIdRoute: typeof AuthenticatedFVisualSuggestionsProductFileIdRoute
  AuthenticatedFTemplateIndexRoute: typeof AuthenticatedFTemplateIndexRoute
}

const AuthenticatedFRouteRouteChildren: AuthenticatedFRouteRouteChildren = {
  AuthenticatedFIndexRoute: AuthenticatedFIndexRoute,
  AuthenticatedFOutputProductFileIdRoute:
    AuthenticatedFOutputProductFileIdRoute,
  AuthenticatedFPromptProductFileIdRoute:
    AuthenticatedFPromptProductFileIdRoute,
  AuthenticatedFSettingsProductFileIdRoute:
    AuthenticatedFSettingsProductFileIdRoute,
  AuthenticatedFUploadProductFileIdRoute:
    AuthenticatedFUploadProductFileIdRoute,
  AuthenticatedFVisualSuggestionsProductFileIdRoute:
    AuthenticatedFVisualSuggestionsProductFileIdRoute,
  AuthenticatedFTemplateIndexRoute: AuthenticatedFTemplateIndexRoute,
}

const AuthenticatedFRouteRouteWithChildren =
  AuthenticatedFRouteRoute._addFileChildren(AuthenticatedFRouteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDemoRouteRoute: typeof AuthenticatedAdminDemoRouteRouteWithChildren
  AuthenticatedChatbotFlowRouteRoute: typeof AuthenticatedChatbotFlowRouteRoute
  AuthenticatedCompanyRouteRoute: typeof AuthenticatedCompanyRouteRoute
  AuthenticatedCreditPlanRouteRoute: typeof AuthenticatedCreditPlanRouteRoute
  AuthenticatedCreditPolicyRouteRoute: typeof AuthenticatedCreditPolicyRouteRoute
  AuthenticatedFRouteRoute: typeof AuthenticatedFRouteRouteWithChildren
  AuthenticatedHomepageFlowRouteRoute: typeof AuthenticatedHomepageFlowRouteRoute
  AuthenticatedReferralEventRouteRoute: typeof AuthenticatedReferralEventRouteRoute
  AuthenticatedReviewRouteRoute: typeof AuthenticatedReviewRouteRoute
  AuthenticatedStartRouteRoute: typeof AuthenticatedStartRouteRoute
  AuthenticatedStart2RouteRoute: typeof AuthenticatedStart2RouteRoute
  AuthenticatedCDetailInputRouteRoute: typeof AuthenticatedCDetailInputRouteRoute
  AuthenticatedDPreviewRouteRoute: typeof AuthenticatedDPreviewRouteRoute
  AuthenticatedCProductIdRoute: typeof AuthenticatedCProductIdRoute
  AuthenticatedDProductFileIdRoute: typeof AuthenticatedDProductFileIdRoute
  AuthenticatedPaymentFailRoute: typeof AuthenticatedPaymentFailRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
  AuthenticatedCIndexRoute: typeof AuthenticatedCIndexRoute
  AuthenticatedDIndexRoute: typeof AuthenticatedDIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDemoRouteRoute:
    AuthenticatedAdminDemoRouteRouteWithChildren,
  AuthenticatedChatbotFlowRouteRoute: AuthenticatedChatbotFlowRouteRoute,
  AuthenticatedCompanyRouteRoute: AuthenticatedCompanyRouteRoute,
  AuthenticatedCreditPlanRouteRoute: AuthenticatedCreditPlanRouteRoute,
  AuthenticatedCreditPolicyRouteRoute: AuthenticatedCreditPolicyRouteRoute,
  AuthenticatedFRouteRoute: AuthenticatedFRouteRouteWithChildren,
  AuthenticatedHomepageFlowRouteRoute: AuthenticatedHomepageFlowRouteRoute,
  AuthenticatedReferralEventRouteRoute: AuthenticatedReferralEventRouteRoute,
  AuthenticatedReviewRouteRoute: AuthenticatedReviewRouteRoute,
  AuthenticatedStartRouteRoute: AuthenticatedStartRouteRoute,
  AuthenticatedStart2RouteRoute: AuthenticatedStart2RouteRoute,
  AuthenticatedCDetailInputRouteRoute: AuthenticatedCDetailInputRouteRoute,
  AuthenticatedDPreviewRouteRoute: AuthenticatedDPreviewRouteRoute,
  AuthenticatedCProductIdRoute: AuthenticatedCProductIdRoute,
  AuthenticatedDProductFileIdRoute: AuthenticatedDProductFileIdRoute,
  AuthenticatedPaymentFailRoute: AuthenticatedPaymentFailRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
  AuthenticatedCIndexRoute: AuthenticatedCIndexRoute,
  AuthenticatedDIndexRoute: AuthenticatedDIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface IntroAuthenticatedRouteChildren {
  IntroAuthenticatedSelectOnboardingIndexRoute: typeof IntroAuthenticatedSelectOnboardingIndexRoute
}

const IntroAuthenticatedRouteChildren: IntroAuthenticatedRouteChildren = {
  IntroAuthenticatedSelectOnboardingIndexRoute:
    IntroAuthenticatedSelectOnboardingIndexRoute,
}

const IntroAuthenticatedRouteWithChildren =
  IntroAuthenticatedRoute._addFileChildren(IntroAuthenticatedRouteChildren)

interface IntroRouteChildren {
  IntroAuthenticatedRoute: typeof IntroAuthenticatedRouteWithChildren
  IntroPasswordResetRoute: typeof IntroPasswordResetRoute
  IntroSignUpRoute: typeof IntroSignUpRoute
}

const IntroRouteChildren: IntroRouteChildren = {
  IntroAuthenticatedRoute: IntroAuthenticatedRouteWithChildren,
  IntroPasswordResetRoute: IntroPasswordResetRoute,
  IntroSignUpRoute: IntroSignUpRoute,
}

const IntroRouteWithChildren = IntroRoute._addFileChildren(IntroRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  IntroRoute: IntroRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
